### PR TITLE
Added support for React 17 & 18

### PR DESCRIPTION
**Pull request by Cl00e9ment**

### CODE REVIEW

**Comment by jessy1092** [comment]
@Cl00e9ment Nice job.

Could you modify the commit message with [Angular commit message format](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format)? Thanks

Like
`fix: added support for React 17 & 18`

**Comment by Cl00e9ment** [comment]
Done!

**Comment by Cl00e9ment** [comment]
Thank you for the merge! Can you update NPM please?

**Comment by jessy1092** [comment]
@Cl00e9ment I just publish `v0.7.1`. Please try again. :)

https://www.npmjs.com/package/react-github-fork-ribbon

**Comment by Cl00e9ment** [comment]
It's all good, thank!

**Pull request merged**
